spring:
  application:
    name: fund-management

  datasource:
    url: jdbc:postgresql://localhost:5432/mutual_fund_management
    username: postgres
    password: 3112
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090

